# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import controller_pb2 as controller__pb2


class StringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendString = channel.unary_unary(
                '/example.StringService/SendString',
                request_serializer=controller__pb2.StringRequest.SerializeToString,
                response_deserializer=controller__pb2.StringReply.FromString,
                )


class StringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendString': grpc.unary_unary_rpc_method_handler(
                    servicer.SendString,
                    request_deserializer=controller__pb2.StringRequest.FromString,
                    response_serializer=controller__pb2.StringReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.StringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.StringService/SendString',
            controller__pb2.StringRequest.SerializeToString,
            controller__pb2.StringReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
