# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\x07\x65xample\" \n\rStringRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bStringReply\x12\x0f\n\x07message\x18\x01 \x01(\t2M\n\rStringService\x12<\n\nSendString\x12\x16.example.StringRequest\x1a\x14.example.StringReply\"\x00\x42\x08Z\x06../genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006../gen'
  _globals['_STRINGREQUEST']._serialized_start=29
  _globals['_STRINGREQUEST']._serialized_end=61
  _globals['_STRINGREPLY']._serialized_start=63
  _globals['_STRINGREPLY']._serialized_end=93
  _globals['_STRINGSERVICE']._serialized_start=95
  _globals['_STRINGSERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
