# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: m1.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08m1.proto\x12\x07service\"\x80\x01\n\nSumRequest\x12\x13\n\x06\x61\x63tion\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04port\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04num1\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12\x11\n\x04num2\x18\x04 \x01(\x03H\x03\x88\x01\x01\x42\t\n\x07_actionB\x07\n\x05_portB\x07\n\x05_num1B\x07\n\x05_num2\"@\n\x0bSumResponse\x12\x0f\n\x07\x63onnect\x18\x01 \x01(\x08\x12\x14\n\x07success\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_success2B\n\nSumService\x12\x34\n\x03Sum\x12\x13.service.SumRequest\x1a\x14.service.SumResponse(\x01\x30\x01\x42\x08Z\x06../genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'm1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006../gen'
  _globals['_SUMREQUEST']._serialized_start=22
  _globals['_SUMREQUEST']._serialized_end=150
  _globals['_SUMRESPONSE']._serialized_start=152
  _globals['_SUMRESPONSE']._serialized_end=216
  _globals['_SUMSERVICE']._serialized_start=218
  _globals['_SUMSERVICE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
