# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sumgo.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsumgo.proto\x12\x07service\"=\n\x0f\x44oActionRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x11\n\x04port\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_port\"?\n\x10\x44oActionResponse\x12\x11\n\x04\x64\x61ta\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07success\x18\x02 \x01(\tB\x07\n\x05_data\"(\n\nSumRequest\x12\x0c\n\x04num1\x18\x03 \x01(\x03\x12\x0c\n\x04num2\x18\x04 \x01(\x03\":\n\x0bSumResponse\x12\x11\n\x04\x64\x61ta\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07success\x18\x02 \x01(\tB\x07\n\x05_data2\x83\x01\n\nSumService\x12\x34\n\x03Sum\x12\x13.service.SumRequest\x1a\x14.service.SumResponse(\x01\x30\x01\x12?\n\x08\x44oAction\x12\x18.service.DoActionRequest\x1a\x19.service.DoActionResponseB\x08Z\x06../genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sumgo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006../gen'
  _globals['_DOACTIONREQUEST']._serialized_start=24
  _globals['_DOACTIONREQUEST']._serialized_end=85
  _globals['_DOACTIONRESPONSE']._serialized_start=87
  _globals['_DOACTIONRESPONSE']._serialized_end=150
  _globals['_SUMREQUEST']._serialized_start=152
  _globals['_SUMREQUEST']._serialized_end=192
  _globals['_SUMRESPONSE']._serialized_start=194
  _globals['_SUMRESPONSE']._serialized_end=252
  _globals['_SUMSERVICE']._serialized_start=255
  _globals['_SUMSERVICE']._serialized_end=386
# @@protoc_insertion_point(module_scope)
