# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sumgo_pb2 as sumgo__pb2


class SumServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sum = channel.stream_stream(
                '/service.SumService/Sum',
                request_serializer=sumgo__pb2.SumRequest.SerializeToString,
                response_deserializer=sumgo__pb2.SumResponse.FromString,
                )
        self.DoAction = channel.unary_unary(
                '/service.SumService/DoAction',
                request_serializer=sumgo__pb2.DoActionRequest.SerializeToString,
                response_deserializer=sumgo__pb2.DoActionResponse.FromString,
                )


class SumServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sum(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SumServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sum': grpc.stream_stream_rpc_method_handler(
                    servicer.Sum,
                    request_deserializer=sumgo__pb2.SumRequest.FromString,
                    response_serializer=sumgo__pb2.SumResponse.SerializeToString,
            ),
            'DoAction': grpc.unary_unary_rpc_method_handler(
                    servicer.DoAction,
                    request_deserializer=sumgo__pb2.DoActionRequest.FromString,
                    response_serializer=sumgo__pb2.DoActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.SumService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SumService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sum(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/service.SumService/Sum',
            sumgo__pb2.SumRequest.SerializeToString,
            sumgo__pb2.SumResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DoAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.SumService/DoAction',
            sumgo__pb2.DoActionRequest.SerializeToString,
            sumgo__pb2.DoActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
